[package]
name = "zerotrace-split"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sharks = "0.5"
serde.workspace = true
sha2.workspace = true
uuid.workspace = true
zerotrace-core = { path = "../zerotrace-core" }
zerotrace-crypto = { path = "../zerotrace-crypto" }
zerotrace-kdf = { path = "../zerotrace-kdf" }
zerotrace-secure-memory = { path = "../zerotrace-secure-memory" }
